
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygcdksdsleyazlxfjpid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnY2Rrc2RzbGV5YXpseGZqcGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mjk1NDQsImV4cCI6MjA2NzMwNTU0NH0.7CR7OpLgYElfXNw4YeXJ7tPt8CAakzMLZmqTtfiRHMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
